using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TRANSMARIZE.Model
{
    public partial class ShareData : ObservableObject
    {
        // các biến được sử dụng chung bởi các views
        public static string transText = string.Empty;
        public static string langSecond = "vi";
        public static Dictionary<string, string> languageDictionary = new Dictionary<string, string>
        {
            {"Afrikaans", "af"},
            {"Albanian", "sq"},
            {"Amharic", "am"},
            {"Arabic", "ar"},
            {"Azerbaijani", "az"},
            {"Bengali", "bn"},
            {"Bosnian", "bs"},
            {"Catalan", "ca"},
            {"Chinese (Simplified)", "zh-CN"},
            {"Chinese (Traditional)", "zh-TW"},
            {"Croatian", "hr"},
            {"Czech", "cs"},
            {"Danish", "da"},
            {"Dutch", "nl"},
            {"English", "en"},
            {"Esperanto", "eo"},
            {"Estonian", "et"},
            {"Finnish", "fi"},
            {"French", "fr"},
            {"Galician", "gl"},
            {"German", "de"},
            {"Greek", "el"},
            {"Gujarati", "gu"},
            {"Haitian Creole", "ht"},
            {"Hebrew", "he"},
            {"Hindi", "hi"},
            {"Hungarian", "hu"},
            {"Icelandic", "is"},
            {"Indonesian", "id"},
            {"Irish", "ga"},
            {"Italian", "it"},
            {"Japanese", "ja"},
            {"Kannada", "kn"},
            {"Kazakh", "kk"},
            {"Korean", "ko"},
            {"Latvian", "lv"},
            {"Lithuanian", "lt"},
            {"Macedonian", "mk"},
            {"Malay", "ms"},
            {"Malayalam", "ml"},
            {"Maltese", "mt"},
            {"Marathi", "mr"},
            {"Nepali", "ne"},
            {"Norwegian", "no"},
            {"Persian", "fa"},
            {"Polish", "pl"},
            {"Portuguese", "pt"},
            {"Punjabi", "pa"},
            {"Romanian", "ro"},
            {"Russian", "ru"},
            {"Serbian", "sr"},
            {"Slovak", "sk"},
            {"Slovenian", "sl"},
            {"Spanish", "es"},
            {"Swahili", "sw"},
            {"Swedish", "sv"},
            {"Tamil", "ta"},
            {"Telugu", "te"},
            {"Thai", "th"},
            {"Turkish", "tr"},
            {"Ukrainian", "uk"},
            {"Urdu", "ur"},
            {"Vietnamese", "vi"},
            {"Welsh", "cy"},
            {"Yiddish", "yi"},
            {"Zulu", "zu"}
        };

        [ObservableProperty]
        private List<string> languageList = new List<string>
        {
            "Afrikaans", 
            "Albanian",
            "Amharic", 
            "Arabic", 
            "Azerbaijani",
            "Bengali", 
            "Bosnian", 
            "Catalan",
            "Chinese (Simplified)",
            "Chinese (Traditional)",
            "Croatian", 
            "Czech", 
            "Danish", 
            "Dutch", 
            "English", 
            "Esperanto", 
            "Estonian", 
            "Finnish", 
            "French", 
            "Galician", 
            "German", 
            "Greek", 
            "Gujarati", 
            "Hebrew", 
            "Hindi", 
            "Hungarian", 
            "Icelandic", 
            "Indonesian",
            "Irish", 
            "Italian", 
            "Japanese", 
            "Kannada", 
            "Kazakh", 
            "Korean", 
            "Latvian",
            "Lithuanian",
            "Macedonian",
            "Malay", 
            "Malayalam", 
            "Maltese", 
            "Marathi",
            "Nepali", 
            "Norwegian", 
            "Persian", 
            "Polish", 
            "Portuguese",
            "Punjabi", 
            "Romanian", 
            "Russian", 
            "Serbian",
            "Slovak", 
            "Slovenian", 
            "Spanish", 
            "Swahili", 
            "Swedish", 
            "Tamil", 
            "Telugu", 
            "Thai", 
            "Turkish", 
            "Ukrainian", 
            "Urdu", 
            "Vietnamese",
            "Welsh", 
            "Yiddish", 
            "Zulu", 
        };
    }

}
 